version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - .:/var/www/project
    expose:
      - "9001"
    ports:
      - 8000:8000
    networks:
      - symfony
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"       
    volumes:
      - mysql-db-data:/var/lib/mysql 
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: movedb 
    networks:
      - symfony

networks:
  symfony:

volumes:  
  mysql-db-data: