-- MySQL Script generated by MySQL Workbench
-- Thu Aug  5 10:11:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movedb` ;
USE `movedb` ;

-- -----------------------------------------------------
-- Table `movedb`.`agrupador1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`agrupador1` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_agrupador` TINYINT(3) NULL,
  `descripcion` VARCHAR(60) NULL DEFAULT NULL,
  INDEX (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`agrupador2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`agrupador2` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_agrupador` TINYINT(3) NULL,
  `descripcion` VARCHAR(60) NULL DEFAULT NULL,
  INDEX (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`auditoria` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_interfaz` TINYINT(3) NULL DEFAULT 0,
  `programa` VARCHAR(10) NULL DEFAULT NULL,
  `id_registro` DOUBLE NULL DEFAULT NULL,
  `campo_cambiado` VARCHAR(30) NULL DEFAULT NULL,
  `campo_cambiado_de` LONGTEXT NULL DEFAULT NULL,
  `campo_cambiado_a` LONGTEXT NULL DEFAULT NULL,
  `usuario` VARCHAR(15) NULL DEFAULT NULL,
  `nombre_equipo` VARCHAR(15) NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NULL DEFAULT NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`remesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`remesa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activado1` VARCHAR(1) NULL DEFAULT NULL,
  `activado2` VARCHAR(1) NULL DEFAULT NULL,
  `remesa` VARCHAR(15) NULL DEFAULT NULL,
  `codigo_NC` VARCHAR(10) NULL DEFAULT NULL,
  UNIQUE INDEX (`remesa` ASC) ,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tipo_documento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(3) NULL DEFAULT NULL,
  `descripcion` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`casilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`casilla` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`cia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`cia` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`auxiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`auxiliar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupo1` TINYINT(3) NULL DEFAULT 0,
  `orden1` INT NULL DEFAULT 0,
  `orden2` INT NULL DEFAULT 0,
  `activado1` VARCHAR(1) NULL DEFAULT NULL,
  `auxiliar1` INT NULL DEFAULT 0,
  `tipo_auxiliar1` VARCHAR(1) NULL DEFAULT NULL,
  `auxiliar2` INT NULL DEFAULT 0,
  `tipo_auxiliar2` VARCHAR(1) NULL DEFAULT NULL,
  `auxiliar3` INT NULL DEFAULT 0,
  `cia` VARCHAR(5) NULL DEFAULT NULL,
  `cuenta_objeto` VARCHAR(6) NULL DEFAULT NULL,
  `cuenta_aux1` VARCHAR(4) NULL DEFAULT NULL,
  `cuenta_aux2` VARCHAR(4) NULL DEFAULT NULL,
  `codigo1` VARCHAR(15) NULL,
  `nombre_auxiliar1` VARCHAR(50) NULL,
  `nombre_auxiliar2` VARCHAR(50) NULL,
  `nombre_auxiliar3` VARCHAR(255) NULL DEFAULT NULL,
  `categoria1` TINYINT(3) NULL DEFAULT NULL,
  `categoria2` TINYINT(3) NULL DEFAULT NULL,
  `categoria3` TINYINT(3) NULL DEFAULT NULL,
  `activado2` VARCHAR(1) NULL DEFAULT NULL,
  `activado3` VARCHAR(1) NULL DEFAULT NULL,
  `activado4` VARCHAR(1) NULL DEFAULT NULL,
  `activado5` VARCHAR(1) NULL DEFAULT NULL,
  `notas` LONGTEXT NULL DEFAULT NULL,
  `remesa_id` INT(11) NOT NULL,
  `tipo_documento_id` INT(11) NOT NULL,
  `casilla_id` INT(11) NOT NULL,
  `cia_id` INT(11) NOT NULL,
  INDEX (`id` ASC) ,
  INDEX (`cuenta_aux2` ASC) ,
  INDEX (`cuenta_aux1` ASC) ,
  INDEX (`cia` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_auxiliar_remesa_idx` (`remesa_id` ASC) ,
  INDEX `fk_auxiliar_tipo_documento1_idx` (`tipo_documento_id` ASC) ,
  INDEX `fk_auxiliar_casilla1_idx` (`casilla_id` ASC) ,
  INDEX `fk_auxiliar_cia1_idx` (`cia_id` ASC) ,
  CONSTRAINT `fk_auxiliar_remesa`
    FOREIGN KEY (`remesa_id`)
    REFERENCES `movedb`.`remesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auxiliar_tipo_documento1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `movedb`.`tipo_documento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auxiliar_casilla1`
    FOREIGN KEY (`casilla_id`)
    REFERENCES `movedb`.`casilla` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auxiliar_cia1`
    FOREIGN KEY (`cia_id`)
    REFERENCES `movedb`.`cia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`banco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activo` VARCHAR(1) NULL DEFAULT NULL,
  `orden` INT NULL DEFAULT 0,
  `codigo_banco` INT NULL,
  `nombre_banco` VARCHAR(30) NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`categoria_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`categoria_cuenta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`categoria_saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`categoria_saldo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`Cias1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`Cias1` (
  `Id` VARCHAR(5) NOT NULL,
  `Activado` VARCHAR(1) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`criterio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`criterio` (
  `id` INT(11) NOT NULL,
  `documento` VARCHAR(30) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX (`id` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`producto` (
  `cod_producto` INT NOT NULL AUTO_INCREMENT,
  `descripcion_producto` VARCHAR(15) NULL,
  `observacion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_producto`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`cuenta` (
  `id` INT(11) NOT NULL,
  `chequeo` TINYINT(1) NULL DEFAULT 0,
  `activado1` VARCHAR(1) NULL DEFAULT NULL,
  `activado2` VARCHAR(1) NULL DEFAULT NULL,
  `activado3` VARCHAR(1) NULL DEFAULT NULL,
  `activado4` VARCHAR(1) NULL DEFAULT NULL,
  `categoria3` INT NULL DEFAULT 0,
  `categoria4` LONGTEXT NULL DEFAULT NULL,
  `codigo_cuenta_jde` VARCHAR(10) NULL DEFAULT NULL,
  `cuenta_objeto` VARCHAR(6) NULL DEFAULT NULL,
  `cuenta_auxiliar` VARCHAR(4) NULL DEFAULT NULL,
  `cuenta_contable` VARCHAR(25) NULL DEFAULT NULL,
  `cuenta_bancaria` VARCHAR(50) NULL DEFAULT NULL,
  `cta_corta` VARCHAR(5) NULL DEFAULT NULL,
  `auxiliar` VARCHAR(6) NULL DEFAULT NULL,
  `tipo_auxiliar` VARCHAR(1) NULL DEFAULT NULL,
  `cuenta_descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  `observacione` LONGTEXT NULL DEFAULT NULL,
  `orden1` INT NULL DEFAULT 0,
  `cta_extracto` VARCHAR(50) NULL DEFAULT NULL,
  `cta_rp_saldos` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_apertura` DATETIME NULL DEFAULT NULL,
  `exenta` VARCHAR(1) NULL DEFAULT NULL,
  `fecha_exencion` DATETIME NULL DEFAULT NULL,
  `area` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion_saldos` LONGTEXT NULL DEFAULT NULL,
  `estado_cta` VARCHAR(1) NULL DEFAULT NULL,
  `agrupador22` LONGTEXT NULL DEFAULT NULL,
  `respaldo` TINYINT(3) NULL DEFAULT NULL,
  `categoria_cuenta_id` INT(11) NOT NULL,
  `categoria_saldo_id` INT(11) NOT NULL,
  `cia_id` INT(11) NOT NULL,
  `producto_cod_producto` INT NOT NULL,
  `agrupador2_id` INT(11) NOT NULL,
  `agrupador1_id` INT(11) NOT NULL,
  `banco_id` INT(11) NOT NULL,
  UNIQUE INDEX (`codigo_cuenta_jde` ASC) ,
  INDEX (`cuenta_contable` ASC) ,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_cuenta_categoria_cuenta1_idx` (`categoria_cuenta_id` ASC) ,
  INDEX `fk_cuenta_categoria_saldo1_idx` (`categoria_saldo_id` ASC) ,
  INDEX `fk_cuenta_cia1_idx` (`cia_id` ASC) ,
  INDEX `fk_cuenta_producto1_idx` (`producto_cod_producto` ASC) ,
  INDEX `fk_cuenta_agrupador21_idx` (`agrupador2_id` ASC) ,
  INDEX `fk_cuenta_agrupador11_idx` (`agrupador1_id` ASC) ,
  INDEX `fk_cuenta_banco1_idx` (`banco_id` ASC) ,
  CONSTRAINT `fk_cuenta_categoria_cuenta1`
    FOREIGN KEY (`categoria_cuenta_id`)
    REFERENCES `movedb`.`categoria_cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_categoria_saldo1`
    FOREIGN KEY (`categoria_saldo_id`)
    REFERENCES `movedb`.`categoria_saldo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_cia1`
    FOREIGN KEY (`cia_id`)
    REFERENCES `movedb`.`cia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_producto1`
    FOREIGN KEY (`producto_cod_producto`)
    REFERENCES `movedb`.`producto` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_agrupador21`
    FOREIGN KEY (`agrupador2_id`)
    REFERENCES `movedb`.`agrupador2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_agrupador11`
    FOREIGN KEY (`agrupador1_id`)
    REFERENCES `movedb`.`agrupador1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_banco1`
    FOREIGN KEY (`banco_id`)
    REFERENCES `movedb`.`banco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`estado` (
  `id` INT NULL DEFAULT 0,
  `cod_estado` VARCHAR(1) NOT NULL,
  `descripcion_estado` VARCHAR(10) NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`cod_estado`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`estado_gestion_pago_efectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`estado_gestion_pago_efectivo` (
  `id` INT(11) NOT NULL,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `codigo_estado` VARCHAR(2) NULL,
  `descripcion_estado` VARCHAR(50) NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`forma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`forma` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NULL,
  `orden_forma` TINYINT(3) NULL DEFAULT NULL,
  `forma` VARCHAR(50) NULL,
  `orden_categoria_forma` TINYINT(3) NULL DEFAULT 0,
  `categoria_forma` VARCHAR(50) NULL,
  `categoria1` VARCHAR(7) NULL DEFAULT NULL,
  `activado1` VARCHAR(1) NULL DEFAULT NULL,
  `activado2` VARCHAR(1) NULL,
  `activado3` VARCHAR(1) NULL,
  `activado4` VARCHAR(1) NULL DEFAULT NULL,
  `signo` INT NULL,
  `notas` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(15) NULL,
  `clave` VARCHAR(15) NULL,
  `nombre` VARCHAR(50) NULL,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `en_uso` VARCHAR(1) NULL DEFAULT 'N',
  `cedula` INT(15) NULL,
  INDEX (`clave` ASC) ,
  PRIMARY KEY (`id`),
  INDEX (`usuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`secuencia_registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`secuencia_registro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_lote` INT NULL DEFAULT NULL,
  `id_registro` INT NULL,
  `id_interfaz` TINYINT(3) NULL DEFAULT 0,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_secuencia_registro_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_secuencia_registro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`gestion_registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`gestion_registro` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `chequeo` TINYINT(1) NULL DEFAULT 0,
  `mk` TINYINT(1) NULL DEFAULT 0,
  `id_interfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `id_lote` INT NULL DEFAULT NULL,
  `id_control` INT NULL DEFAULT NULL,
  `fecha_ingreso` DATETIME NULL DEFAULT NULL,
  `fecha_LM` DATETIME NULL DEFAULT NULL,
  `importe` DOUBLE NULL DEFAULT 0,
  `id_control1` VARCHAR(15) NULL DEFAULT NULL,
  `id_control2` INT NULL DEFAULT NULL,
  `fecha_control1` DATETIME NULL DEFAULT NULL,
  `notas` LONGTEXT NULL DEFAULT NULL,
  `observaciones` VARCHAR(30) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `marca_banco` VARCHAR(1) NULL DEFAULT 'N',
  `num_batch` INT NULL DEFAULT NULL,
  `num_documento` INT NULL DEFAULT NULL,
  `bloqueo` VARCHAR(1) NULL DEFAULT 'N',
  `forma_id` INT(11) NOT NULL,
  `auxiliar_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `secuencia_registro_id` INT(11) NOT NULL,
  `cuenta_id` INT(11) NOT NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_gestion_registro_forma1_idx` (`forma_id` ASC) ,
  INDEX `fk_gestion_registro_auxiliar1_idx` (`auxiliar_id` ASC) ,
  INDEX `fk_gestion_registro_usuario1_idx` (`usuario_id` ASC) ,
  INDEX `fk_gestion_registro_secuencia_registro1_idx` (`secuencia_registro_id` ASC) ,
  INDEX `fk_gestion_registro_cuenta1_idx` (`cuenta_id` ASC) ,
  CONSTRAINT `fk_gestion_registro_forma1`
    FOREIGN KEY (`forma_id`)
    REFERENCES `movedb`.`forma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestion_registro_auxiliar1`
    FOREIGN KEY (`auxiliar_id`)
    REFERENCES `movedb`.`auxiliar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestion_registro_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestion_registro_secuencia_registro1`
    FOREIGN KEY (`secuencia_registro_id`)
    REFERENCES `movedb`.`secuencia_registro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestion_registro_cuenta1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `movedb`.`cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`objeto` (
  `IdObjeto` VARCHAR(10) NOT NULL,
  `orden` INT NULL DEFAULT NULL,
  `codigo_objeto` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `tipo_objeto` VARCHAR(10) NULL DEFAULT NULL,
  `nombre_objeto_sistema` VARCHAR(50) NULL,
  `nombre_objeto_alterno` VARCHAR(100) NULL DEFAULT NULL,
  `categoria_adm` VARCHAR(1) NULL DEFAULT NULL,
  `categoria0` VARCHAR(1) NULL DEFAULT NULL,
  `categoria1` VARCHAR(1) NULL DEFAULT NULL,
  `categoria2` VARCHAR(1) NULL DEFAULT NULL,
  `observacion` VARCHAR(255) NULL DEFAULT NULL,
  `remesa_id` INT(11) NOT NULL,
  INDEX (`IdObjeto` ASC) ,
  PRIMARY KEY (`IdObjeto`),
  INDEX `fk_objeto_remesa1_idx` (`remesa_id` ASC) ,
  CONSTRAINT `fk_objeto_remesa1`
    FOREIGN KEY (`remesa_id`)
    REFERENCES `movedb`.`remesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`pago_efectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`pago_efectivo` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Chequeo` TINYINT(1) NULL DEFAULT 0,
  `TipoDoc` VARCHAR(2) NULL DEFAULT NULL,
  `IdControl` VARCHAR(20) NULL DEFAULT NULL,
  `NumeroPago` INT NULL DEFAULT 0,
  `FechaPago` DATETIME NULL DEFAULT NULL,
  `FechaLM` DATETIME NULL DEFAULT NULL,
  `Beneficiario` VARCHAR(100) NULL DEFAULT NULL,
  `importe` INT NULL DEFAULT 0,
  `numero_documento` INT NULL DEFAULT NULL,
  `estado` VARCHAR(1) NULL DEFAULT 'N',
  `fecha_entrega` DATETIME NULL DEFAULT NULL,
  `notas` LONGTEXT NULL DEFAULT NULL,
  `notas2` LONGTEXT NULL DEFAULT NULL,
  `fecha_importacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  `estado_gestion_pago_efectivo_id` INT(11) NOT NULL,
  `cia_id` INT(11) NOT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdControl` ASC) ,
  INDEX `fk_pago_efectivo_usuario1_idx` (`usuario_id` ASC) ,
  INDEX `fk_pago_efectivo_estado_gestion_pago_efectivo1_idx` (`estado_gestion_pago_efectivo_id` ASC) ,
  INDEX `fk_pago_efectivo_cia1_idx` (`cia_id` ASC) ,
  CONSTRAINT `fk_pago_efectivo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_efectivo_estado_gestion_pago_efectivo1`
    FOREIGN KEY (`estado_gestion_pago_efectivo_id`)
    REFERENCES `movedb`.`estado_gestion_pago_efectivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_efectivo_cia1`
    FOREIGN KEY (`cia_id`)
    REFERENCES `movedb`.`cia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`parametro_traslado_Bco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`parametro_traslado_Bco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cta_origen` INT(11) NULL DEFAULT NULL,
  `cta_destino` INT(11) NULL DEFAULT NULL,
  `documento` VARCHAR(5) NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`periodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_referencia` INT NULL DEFAULT 0,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_inicial` DATETIME NULL DEFAULT NULL,
  `fecha_final` DATETIME NULL DEFAULT NULL,
  `notas` LONGTEXT NULL DEFAULT NULL,
  INDEX (`id_referencia` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`permiso` (
  `id` INT NOT NULL,
  `modulo` VARCHAR(50) NULL,
  `permiso` VARCHAR(1) NULL DEFAULT NULL,
  `nota` VARCHAR(255) NULL DEFAULT NULL,
  `usuario_id` INT(11) NOT NULL,
  INDEX (`modulo` ASC) ,
  INDEX (`id` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_permiso_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_permiso_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`Saldos Diarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`Saldos Diarios` (
  `CIA` DOUBLE NULL DEFAULT NULL,
  `JDE` VARCHAR(255) NULL DEFAULT NULL,
  `AREA` VARCHAR(255) NULL DEFAULT NULL,
  `BANCO` VARCHAR(255) NULL DEFAULT NULL,
  `PRODUCTO` VARCHAR(255) NULL DEFAULT NULL,
  `RESPALDO` VARCHAR(255) NULL DEFAULT NULL,
  `CTA` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`soporte_aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`soporte_aplicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chequeo` TINYINT(1) NULL DEFAULT 0,
  `importe_soporte` INT NULL DEFAULT 0,
  `fecha_soporte` DATETIME NULL DEFAULT NULL,
  `importe_niquel` INT NULL DEFAULT 0,
  `importe_otros` INT NULL DEFAULT 0,
  `importe_aplicar` INT NULL DEFAULT 0,
  `importe_aplicado_rm` INT NULL DEFAULT 0,
  `importe_aplicado` INT NULL DEFAULT 0,
  `fecha_aplicación` DATETIME NULL DEFAULT NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `bloqueo` VARCHAR(1) NULL DEFAULT 'N',
  `remesa_id` INT(11) NOT NULL,
  `forma_id` INT(11) NOT NULL,
  `cuenta_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  INDEX (`id` ASC) ,
  INDEX `fk_soporte_aplicacion_remesa1_idx` (`remesa_id` ASC) ,
  INDEX `fk_soporte_aplicacion_forma1_idx` (`forma_id` ASC) ,
  INDEX `fk_soporte_aplicacion_cuenta1_idx` (`cuenta_id` ASC) ,
  INDEX `fk_soporte_aplicacion_usuario1_idx` (`usuario_id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_soporte_aplicacion_remesa1`
    FOREIGN KEY (`remesa_id`)
    REFERENCES `movedb`.`remesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_aplicacion_forma1`
    FOREIGN KEY (`forma_id`)
    REFERENCES `movedb`.`forma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_aplicacion_cuenta1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `movedb`.`cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soporte_aplicacion_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`TbCasilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`TbCasilla` (
  `UsuarioCasilla` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`UsuarioCasilla`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`TbControlInformes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`TbControlInformes` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `IdRegistro` INT NULL DEFAULT 0,
  `Chequeo` TINYINT(1) NULL DEFAULT 0,
  `Mk` TINYINT(1) NULL DEFAULT 0,
  `IdAuxiliar` INT NULL DEFAULT 0,
  `FechaInforme` DATETIME NULL DEFAULT NULL,
  `FechaRecibo` DATETIME NULL DEFAULT NULL,
  `CodigoEstado` INT NULL DEFAULT 0,
  `CodigoNovedad` INT NULL DEFAULT 0,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `IdUsuarioCheck` INT NULL DEFAULT 0,
  `UsuarioChequea` VARCHAR(15) NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdAuxiliar` ASC) ,
  INDEX (`IdRegistro` ASC) ,
  INDEX (`IdUsuarioCheck` ASC) ,
  INDEX (`IdUsuario` ASC) ,
  INDEX (`CodigoNovedad` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`TbEstadosInforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`TbEstadosInforme` (
  `Activado1` VARCHAR(1) NULL DEFAULT NULL,
  `CodigoEstado` INT NOT NULL,
  `Estado` VARCHAR(50) NOT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  UNIQUE INDEX (`Estado` ASC) ,
  UNIQUE INDEX (`CodigoEstado` ASC) ,
  PRIMARY KEY (`CodigoEstado`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`TbNovedadesInformes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`TbNovedadesInformes` (
  `Orden` INT NULL DEFAULT NULL,
  `Activado1` VARCHAR(1) NULL DEFAULT NULL,
  `CodigoNovedad` INT NOT NULL,
  `Novedad` VARCHAR(100) NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  INDEX (`Novedad` ASC) ,
  PRIMARY KEY (`CodigoNovedad`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tiempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tiempo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_referencia` INT NULL DEFAULT 0,
  `referencia` VARCHAR(30) NULL DEFAULT NULL,
  `tiempo` INT NULL DEFAULT 0,
  `nota` LONGTEXT NULL DEFAULT NULL,
  INDEX (`id_referencia` ASC) ,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpAuditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpAuditoria` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `Programa` VARCHAR(10) NULL DEFAULT NULL,
  `IdRegistro` DOUBLE NULL DEFAULT NULL,
  `Campo_Cambiado` VARCHAR(30) NULL DEFAULT NULL,
  `Campo_Cambiado_De` LONGTEXT NULL DEFAULT NULL,
  `Campo_Cambiado_A` LONGTEXT NULL DEFAULT NULL,
  `Usuario` VARCHAR(15) NULL DEFAULT NULL,
  `Nombre_Equipo` VARCHAR(15) NULL DEFAULT NULL,
  `Fecha_Modificacion` DATETIME NULL DEFAULT NULL,
  INDEX (`Id` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpCompEfectivoxNumeroDoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpCompEfectivoxNumeroDoc` (
  `Cia` VARCHAR(5) NULL DEFAULT NULL,
  `NumeroPago` INT NULL DEFAULT NULL,
  `FechaPago` DATETIME NULL DEFAULT NULL,
  `Beneficiario` VARCHAR(30) NULL DEFAULT NULL,
  `Importe` INT NULL DEFAULT NULL,
  `NumeroDocumento` INT NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpEdicionRegistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpEdicionRegistro` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdLote` INT NULL DEFAULT NULL,
  `IdRegistro` INT NOT NULL,
  `IdControl` INT NULL DEFAULT NULL,
  `IdForma` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdAuxiliar` INT NULL DEFAULT NULL,
  `FechaIngreso` DATETIME NULL DEFAULT NULL,
  `FechaLM` DATETIME NULL DEFAULT NULL,
  `Importe` DOUBLE NULL DEFAULT NULL,
  `IdControl1` VARCHAR(15) NULL DEFAULT NULL,
  `IdControl2` INT NULL DEFAULT NULL,
  `IdCuenta` INT NULL DEFAULT NULL,
  `FechaControl1` DATETIME NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `Observaciones` VARCHAR(30) NULL DEFAULT NULL,
  `MarcaBco` VARCHAR(1) NULL DEFAULT NULL,
  `N°Batch` INT NULL DEFAULT NULL,
  `N°Documento` INT NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdAuxiliar` ASC) ,
  INDEX (`IdControl` ASC) ,
  INDEX (`IdControl1` ASC) ,
  INDEX (`IdControl2` ASC) ,
  INDEX (`IdCuenta` ASC) ,
  INDEX (`IdForma` ASC) ,
  INDEX (`IdInterfaz` ASC) ,
  INDEX (`IdLote` ASC) ,
  UNIQUE INDEX (`IdRegistro` ASC) ,
  INDEX (`IdUsuario` ASC) ,
  PRIMARY KEY (`IdRegistro`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpEdicionRegistroControlInforme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpEdicionRegistroControlInforme` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `IdRegistro` INT NOT NULL DEFAULT 0,
  `Chequeo` TINYINT(1) NULL DEFAULT 0,
  `IdAuxiliar` INT NULL DEFAULT NULL,
  `FechaInforme` DATETIME NULL DEFAULT NULL,
  `FechaRecibo` DATETIME NULL DEFAULT NULL,
  `CodigoEstado` INT NULL DEFAULT NULL,
  `CodigoNovedad` INT NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdAuxiliar` ASC) ,
  INDEX (`IdRegistro` ASC) ,
  INDEX (`IdUsuario` ASC) ,
  PRIMARY KEY (`IdRegistro`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpEdicionSoporteAplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpEdicionSoporteAplicacion` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `IdSoporte` INT NULL DEFAULT NULL,
  `IdRemesa` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdTipoSoporte` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdCuentaBancaria` INT NULL DEFAULT NULL,
  `ImporteSoporte` INT NULL DEFAULT NULL,
  `FechaSoporte` DATETIME NULL DEFAULT NULL,
  `ImporteNiquel` INT NULL DEFAULT NULL,
  `ImporteOtros` INT NULL DEFAULT NULL,
  `ImporteAplicar` INT NULL DEFAULT NULL,
  `ImporteAplicadoRM` INT NULL DEFAULT NULL,
  `ImporteAplicado` INT NULL DEFAULT NULL,
  `FechaAplicación` DATETIME NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT NULL,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdCuentaBancaria` ASC) ,
  INDEX (`IdRemesa` ASC) ,
  INDEX (`IdSoporte` ASC) ,
  INDEX (`IdTipoSoporte` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpEfectivoPte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpEfectivoPte` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdControl` INT NULL DEFAULT NULL,
  `Remesa` VARCHAR(15) NULL DEFAULT NULL,
  `Cia` VARCHAR(5) NULL DEFAULT NULL,
  `Categoria1` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdAuxiliar` INT NULL DEFAULT NULL,
  `Auxiliar1` INT NULL DEFAULT 0,
  `NombreAuxiliar1` VARCHAR(50) NULL DEFAULT NULL,
  `FechaIngreso` DATETIME NULL DEFAULT NULL,
  `Importe` DOUBLE NULL DEFAULT NULL,
  `ImporteAplicar` INT NULL DEFAULT 0,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  INDEX (`Id` ASC) ,
  INDEX (`IdAuxiliar` ASC) ,
  INDEX (`IdControl` ASC) ,
  INDEX (`IdInterfaz` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpModeloBanco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpModeloBanco` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `IdRegistro` INT NULL DEFAULT 0,
  `Num Cuenta` VARCHAR(255) NULL DEFAULT NULL,
  `LM auxiliar` VARCHAR(255) NULL DEFAULT NULL,
  `Tipo LM auxiliar` VARCHAR(255) NULL DEFAULT NULL,
  `Importe Debito` DOUBLE NULL DEFAULT NULL,
  `Importe Credito` DOUBLE NULL DEFAULT NULL,
  `Descripcion Cuenta` VARCHAR(255) NULL DEFAULT NULL,
  `Fecha Real Documento` DATETIME NULL DEFAULT NULL,
  `Observaciones` VARCHAR(30) NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdRegistro` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovBaucherConciliacion_Vs_JDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovBaucherConciliacion_Vs_JDE` (
  `Sistema` VARCHAR(255) NULL DEFAULT NULL,
  `Tipo Doc` VARCHAR(255) NULL DEFAULT NULL,
  `Fecha Juliana` DOUBLE NULL DEFAULT NULL,
  `Fecha LM` DATETIME NULL DEFAULT NULL,
  `N° Batch` DOUBLE NULL DEFAULT NULL,
  `N° Documento` DOUBLE NULL DEFAULT NULL,
  `Observacion` VARCHAR(255) NULL DEFAULT NULL,
  `Valor` DOUBLE NULL DEFAULT NULL,
  `Cia` VARCHAR(255) NULL DEFAULT NULL,
  `Cta Contable` VARCHAR(255) NULL DEFAULT NULL,
  `Bco` VARCHAR(255) NULL DEFAULT NULL,
  `Cta Bancaria` VARCHAR(255) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(255) NULL DEFAULT NULL,
  `Nº Linea` DOUBLE NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovBcosConciliacion_Vs_JDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovBcosConciliacion_Vs_JDE` (
  `SISTEMA` VARCHAR(15) NULL DEFAULT NULL,
  `TIPO DOC` VARCHAR(2) NULL DEFAULT NULL,
  `OBSERVACION` VARCHAR(30) NULL DEFAULT NULL,
  `AUXILIAR` VARCHAR(8) NULL DEFAULT NULL,
  `AUXILIAR-X` VARCHAR(50) NULL DEFAULT NULL,
  `TIPO AUX` VARCHAR(1) NULL DEFAULT NULL,
  `FECHA LM` DATETIME NULL DEFAULT NULL,
  `IMPORTE` INT NULL DEFAULT NULL,
  `CIA` VARCHAR(2) NULL DEFAULT NULL,
  `CTA OBJETO` VARCHAR(6) NULL DEFAULT NULL,
  `SUBCTA` VARCHAR(8) NULL DEFAULT NULL,
  `CTA` VARCHAR(15) NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(30) NULL DEFAULT NULL,
  `DESCRIPCION CTA BCO` VARCHAR(30) NULL DEFAULT NULL,
  `FECHA REAL DOCTO` VARCHAR(15) NULL DEFAULT NULL,
  `AÑO` INT NULL DEFAULT NULL,
  `MES` INT NULL DEFAULT NULL,
  `Nº LINEA` INT NULL DEFAULT NULL,
  `USUARIO` VARCHAR(10) NULL DEFAULT NULL,
  `Nº BATCH` INT NULL DEFAULT NULL,
  `Nº DOCUMENTO` INT NULL DEFAULT NULL,
  `CONT BATCH` VARCHAR(1) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovCajaConciliacion_Vs_JDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovCajaConciliacion_Vs_JDE` (
  `SISTEMA` VARCHAR(30) NULL DEFAULT NULL,
  `TIPO DOC` VARCHAR(2) NULL DEFAULT NULL,
  `AUXILIAR` VARCHAR(8) NULL DEFAULT NULL,
  `TIPO AUX` VARCHAR(1) NULL DEFAULT NULL,
  `NOMBRE CENTRO COSTO` VARCHAR(40) NULL DEFAULT NULL,
  `FECHA LM` DATETIME NULL DEFAULT NULL,
  `IMPORTE` INT NULL DEFAULT NULL,
  `CIA` VARCHAR(2) NULL DEFAULT NULL,
  `CTA OBJETO` VARCHAR(6) NULL DEFAULT NULL,
  `SUBCTA` VARCHAR(8) NULL DEFAULT NULL,
  `CTA` VARCHAR(15) NULL DEFAULT NULL,
  `AÑO` INT NULL DEFAULT NULL,
  `MES` INT NULL DEFAULT NULL,
  `Nº BATCH` INT NULL DEFAULT NULL,
  `Nº DOCUMENTO` INT NULL DEFAULT NULL,
  `USUARIO` VARCHAR(10) NULL DEFAULT NULL,
  `CONT BATCH` VARCHAR(1) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovIngresosJDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovIngresosJDE` (
  `Tipo Doc` VARCHAR(2) NULL DEFAULT NULL,
  `Tipo Doc2` VARCHAR(2) NULL DEFAULT NULL,
  `Nombre Auxiliar` VARCHAR(100) NULL DEFAULT NULL,
  `Auxiliar` VARCHAR(8) NULL DEFAULT NULL,
  `Tipo Aux` VARCHAR(1) NULL DEFAULT NULL,
  `Importe` DOUBLE NULL DEFAULT NULL,
  `Fch LM` DATETIME NULL DEFAULT NULL,
  `Cta` VARCHAR(29) NULL DEFAULT NULL,
  `Cia` INT NULL DEFAULT 0,
  `Cta Objeto` VARCHAR(6) NULL DEFAULT NULL,
  `Sub Cta` VARCHAR(255) NULL DEFAULT NULL,
  `Des SubCta` VARCHAR(50) NULL DEFAULT NULL,
  `Nº Batch` DECIMAL(8,0) NULL DEFAULT NULL,
  `Nº Doc` DECIMAL(8,0) NULL DEFAULT NULL,
  `Fch Juliana` DECIMAL(6,0) NULL DEFAULT NULL,
  `Año` DECIMAL(2,0) NULL DEFAULT NULL,
  `Mes` DECIMAL(2,0) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovTEConciliacion_Vs_JDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovTEConciliacion_Vs_JDE` (
  `SISTEMA` VARCHAR(15) NULL DEFAULT NULL,
  `TIPO DOC` VARCHAR(2) NULL DEFAULT NULL,
  `OBSERVACION` VARCHAR(30) NULL DEFAULT NULL,
  `AUXILIAR` VARCHAR(8) NULL DEFAULT NULL,
  `AUXILIAR-X` VARCHAR(50) NULL DEFAULT NULL,
  `TIPO AUX` VARCHAR(1) NULL DEFAULT NULL,
  `FECHA LM` DATETIME NULL DEFAULT NULL,
  `IMPORTE` INT NULL DEFAULT 0,
  `CIA` VARCHAR(2) NULL DEFAULT NULL,
  `CTA OBJETO` VARCHAR(6) NULL DEFAULT NULL,
  `SUBCTA` VARCHAR(8) NULL DEFAULT NULL,
  `CTA` VARCHAR(15) NULL DEFAULT NULL,
  `DESCRIPCION` VARCHAR(30) NULL DEFAULT NULL,
  `DESCRIPCION CTA BCO` VARCHAR(30) NULL DEFAULT NULL,
  `FECHA REAL DOCTO` VARCHAR(15) NULL DEFAULT NULL,
  `AÑO` INT NULL DEFAULT 0,
  `MES` INT NULL DEFAULT 0,
  `Nº LINEA` INT NULL DEFAULT 0,
  `USUARIO` VARCHAR(10) NULL DEFAULT NULL,
  `Nº BATCH` INT NULL DEFAULT 0,
  `Nº DOCUMENTO` INT NULL DEFAULT 0,
  `CONT BATCH` VARCHAR(1) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovTjComfamiliarConciliacion_Vs_JDE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovTjComfamiliarConciliacion_Vs_JDE` (
  `Sistema` VARCHAR(255) NULL DEFAULT NULL,
  `Tipo Doc` VARCHAR(2) NULL DEFAULT NULL,
  `Fecha Juliana` DECIMAL(6,0) NULL DEFAULT NULL,
  `Fecha LM` DATETIME NULL DEFAULT NULL,
  `N° Batch` DECIMAL(8,0) NULL DEFAULT NULL,
  `N° Documento` DECIMAL(8,0) NULL DEFAULT NULL,
  `Observacion` VARCHAR(255) NULL DEFAULT NULL,
  `Valor` DECIMAL(28,0) NULL DEFAULT NULL,
  `Cta Contable` VARCHAR(29) NULL DEFAULT NULL,
  `Cta Bancaria` VARCHAR(30) NULL DEFAULT NULL,
  `Cia` INT NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpMovTrasladosBancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpMovTrasladosBancos` (
  `SISTEMA` VARCHAR(15) NULL DEFAULT NULL,
  `TIPO DOC` VARCHAR(5) NULL DEFAULT NULL,
  `OBSERVACION` VARCHAR(30) NULL DEFAULT NULL,
  `FECHA JULIANA` DECIMAL(6,0) NULL DEFAULT NULL,
  `FECHA LM` DATETIME NULL DEFAULT NULL,
  `Nº BATCH` DECIMAL(8,0) NULL DEFAULT NULL,
  `Nº DOCUMENTO` DECIMAL(8,0) NULL DEFAULT NULL,
  `CIA` VARCHAR(12) NULL DEFAULT NULL,
  `CTA OBJETO` VARCHAR(6) NULL DEFAULT NULL,
  `SUBCTA` VARCHAR(8) NULL DEFAULT NULL,
  `IMPORTE` DECIMAL(15,0) NULL DEFAULT NULL,
  `CTA` VARCHAR(29) NULL DEFAULT NULL,
  `CTA BANCARIA` VARCHAR(30) NULL DEFAULT NULL,
  `DESCRIPCION CTA BCO` VARCHAR(30) NULL DEFAULT NULL,
  `AUXILIAR` VARCHAR(8) NULL DEFAULT NULL,
  `TIPO AUX` VARCHAR(1) NULL DEFAULT NULL,
  `MOVIMIENTO` VARCHAR(10) NULL DEFAULT NULL,
  `AÑO` DECIMAL(2,0) NULL DEFAULT NULL,
  `MES` DECIMAL(2,0) NULL DEFAULT NULL,
  `Nº LINEA` INT NULL DEFAULT 0,
  `USUARIO` VARCHAR(10) NULL DEFAULT NULL)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpNvLegalCompEfectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpNvLegalCompEfectivo` (
  `Id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `TipoDoc` VARCHAR(2) NULL DEFAULT NULL,
  `IdControl` VARCHAR(20) NULL DEFAULT NULL,
  `NumeroPago` INT NULL DEFAULT NULL,
  `FechaPago` DATETIME NULL DEFAULT NULL,
  `FechaLM` DATETIME NULL DEFAULT NULL,
  `Cia` VARCHAR(5) NULL DEFAULT NULL,
  `Beneficiario` VARCHAR(30) NULL DEFAULT NULL,
  `Importe` INT NULL DEFAULT NULL,
  `NumeroDocumento` INT NULL DEFAULT NULL,
  `Estado` VARCHAR(1) NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `FechaImportación` DATETIME NULL DEFAULT NULL,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  `IdUsuario` VARCHAR(15) NULL DEFAULT NULL,
  INDEX (`Id` ASC) ,
  INDEX (`IdControl` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpNvSoporteAplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpNvSoporteAplicacion` (
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdSoporte` INT NULL DEFAULT NULL,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `IdRemesa` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdTipoSoporte` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdCuentaBancaria` INT NULL DEFAULT NULL,
  `ImporteSoporte` INT NULL DEFAULT NULL,
  `FechaSoporte` DATETIME NULL DEFAULT NULL,
  `ImporteNiquel` INT NULL DEFAULT NULL,
  `ImporteOtros` INT NULL DEFAULT NULL,
  `ImporteAplicar` INT NULL DEFAULT NULL,
  `ImporteAplicado` INT NULL DEFAULT NULL,
  `FechaAplicación` DATETIME NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`IdCuentaBancaria` ASC) ,
  INDEX (`IdInterfaz` ASC) ,
  INDEX (`IdRemesa` ASC) ,
  INDEX (`IdSoporte` ASC) ,
  INDEX (`IdTipoSoporte` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpPendientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpPendientes` (
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdControl` INT NULL DEFAULT NULL,
  `IdForma` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdForma2` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `Forma` VARCHAR(30) NULL DEFAULT NULL,
  `IdAuxiliar` INT NULL DEFAULT NULL,
  `NombreAuxiliar1` VARCHAR(50) NULL DEFAULT NULL,
  `FechaIngreso` DATETIME NULL DEFAULT NULL,
  `Importe` INT NULL DEFAULT 0,
  `Chequeo` TINYINT(1) NULL DEFAULT NULL,
  `ImporteAplicar` INT NULL DEFAULT NULL,
  `FechaAcreditacion` DATETIME NULL DEFAULT NULL,
  `CuentaBancaria` INT NULL DEFAULT NULL,
  `FechaLM` DATETIME NULL DEFAULT NULL,
  `IdControl1` VARCHAR(15) NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`IdAuxiliar` ASC) ,
  INDEX (`IdControl` ASC) ,
  INDEX (`IdControl1` ASC) ,
  INDEX (`IdForma` ASC) ,
  INDEX (`IdForma2` ASC) ,
  INDEX (`IdInterfaz` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmp_registro_informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmp_registro_informe` (
  `id` INT(11) NULL,
  `id_interfaz` TINYINT(3) NULL DEFAULT 0,
  `id_control1` VARCHAR(15) NULL DEFAULT NULL,
  `fecha_control1` DATETIME NULL DEFAULT NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  `observacion` VARCHAR(30) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NULL DEFAULT NULL,
  `importe` DOUBLE NULL DEFAULT 0,
  `forma_id` INT(11) NOT NULL,
  `cuenta_id` INT(11) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  INDEX (`id` ASC) ,
  INDEX `fk_tmp_registro_informe_forma1_idx` (`forma_id` ASC) ,
  INDEX `fk_tmp_registro_informe_cuenta1_idx` (`cuenta_id` ASC) ,
  INDEX `fk_tmp_registro_informe_usuario1_idx` (`usuario_id` ASC) ,
  CONSTRAINT `fk_tmp_registro_informe_forma1`
    FOREIGN KEY (`forma_id`)
    REFERENCES `movedb`.`forma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tmp_registro_informe_cuenta1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `movedb`.`cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tmp_registro_informe_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `movedb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpRegistrosBancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpRegistrosBancarios` (
  `IdInterfaz` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `Chequeo` TINYINT(1) NULL DEFAULT 0,
  `MarcaBco` VARCHAR(1) NULL DEFAULT NULL,
  `IdRemesa` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `IdCriterio` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `IdRegistro` INT NULL DEFAULT NULL,
  `IdControl` INT NULL DEFAULT 0,
  `IdLote` INT NULL DEFAULT 0,
  `IdForma` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `Forma` VARCHAR(50) NULL DEFAULT NULL,
  `Cia` VARCHAR(5) NULL DEFAULT NULL,
  `CtaObjeto` VARCHAR(6) NULL DEFAULT NULL,
  `CtaAux1` VARCHAR(4) NULL DEFAULT NULL,
  `CtaAux2` VARCHAR(4) NULL DEFAULT NULL,
  `Auxiliar1` VARCHAR(6) NULL DEFAULT NULL,
  `TipoAuxiliar1` VARCHAR(1) NULL DEFAULT NULL,
  `Auxiliar2` VARCHAR(6) NULL DEFAULT NULL,
  `TipoAuxiliar2` VARCHAR(1) NULL DEFAULT NULL,
  `Codigo1` VARCHAR(15) NULL DEFAULT NULL,
  `NombreAuxiliar1` VARCHAR(50) NULL DEFAULT NULL,
  `FechaIngreso` DATETIME NULL DEFAULT NULL,
  `FechaLM` DATETIME NULL DEFAULT NULL,
  `Valor` DOUBLE NULL DEFAULT 0,
  `FechaControl1` DATETIME NULL DEFAULT NULL,
  `IdControl1` VARCHAR(15) NULL DEFAULT NULL,
  `IdControl2` DOUBLE NULL DEFAULT NULL,
  `AuxCtaContable` VARCHAR(6) NULL DEFAULT NULL,
  `TipoAuxCtaContable` VARCHAR(1) NULL DEFAULT NULL,
  `CuentaBcoContable` VARCHAR(25) NULL DEFAULT NULL,
  `CuentaBcoDescripcion` VARCHAR(50) NULL DEFAULT NULL,
  `Notas` LONGTEXT NULL DEFAULT NULL,
  `Observaciones` VARCHAR(30) NULL DEFAULT NULL,
  `IdUsuario` INT NULL DEFAULT 0,
  `FechaActualizacion` DATETIME NULL DEFAULT NULL,
  INDEX (`IdControl` ASC) ,
  INDEX (`IdControl1` ASC) ,
  INDEX (`IdControl2` ASC) ,
  INDEX (`IdCriterio` ASC) ,
  INDEX (`IdForma` ASC) ,
  INDEX (`IdInterfaz` ASC) ,
  INDEX (`IdLote` ASC) ,
  INDEX (`IdRegistro` ASC) ,
  INDEX (`IdRemesa` ASC) ,
  INDEX (`IdUsuario` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`tmpSaldosPendientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`tmpSaldosPendientes` (
  `Año` INT NULL DEFAULT NULL,
  `N° Mes` INT NULL DEFAULT NULL,
  `Nombre Mes` VARCHAR(255) NULL DEFAULT NULL,
  `IdRemesa` TINYINT(3) UNSIGNED NULL DEFAULT 0,
  `Remesa` VARCHAR(15) NULL DEFAULT NULL,
  `Forma` VARCHAR(255) NULL DEFAULT NULL,
  `Cia` VARCHAR(5) NULL DEFAULT NULL,
  `Auxiliar` INT NULL DEFAULT NULL,
  `NombreAuxiliar` VARCHAR(50) NULL DEFAULT NULL,
  `FechaIngreso` DATETIME NULL DEFAULT NULL,
  `Importe` INT NULL DEFAULT NULL,
  `CtaContable` VARCHAR(255) NULL DEFAULT NULL,
  `CtaAux` VARCHAR(4) NULL DEFAULT NULL,
  INDEX (`IdRemesa` ASC) )
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `movedb`.`categoria_cuenta_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movedb`.`categoria_cuenta_copy1` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `activado` VARCHAR(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  `nota` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = myisam
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
